name: outputs

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  # Ziel von outputs: outputs von job1 zu job2 übergeben
  job1:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.schritt1.outputs.test }}
      output2: ${{ steps.schritt1.outputs.test2 }}
    steps:
      # Wir generieren Outputs, die an Job2 übergeben werden
      - id: schritt1
        run: |
          echo "test=hallo" >> "$GITHUB_OUTPUT"
          echo "test2=Welt" >> "$GITHUB_OUTPUT"

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Verwende die Outputs von Job1
        env:
          OUTPUT1: ${{ needs.job1.outputs.output1 }}
          OUTPUT2: ${{ needs.job1.outputs.output2 }}
        run: |
          echo "Output 1: $OUTPUT1"
          echo "Output 2: $OUTPUT2"
